// PRIMITIVE DATA TYPES VS REFERENCE DATA TYPES


// STRINGS //

"HEROKU APP" // AN EXAMPLES OF STRING WHICHS MEANS TEXT WHICH IS NOT MENT TO BE INTERPRETED AS A CODE BUT RATHER AS TEXT INSTEAD OF CODE///



// NUMBERS // 

122343545565678904556675554656 // EXAMPLES OF NUMBERS WHEN WE CALL PRIMITIVE DATA TYPE



// BOOLEANS //


TRUE / FALSE 


// SIDE NOTE WHEN YOU USE THE FUNCTION typeof() IN JAVASCRIPT THIS IS SIMILAR TO type() in python //


// EXAMPLE //

typeof(123)